# Generated by Django 3.2.9 on 2021-11-17 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rarerestapi', '0002_rename_user_id_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rarerestapi.categories'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rarerestapi.rareusers'),
        ),
    ]
