# Generated by Django 3.2.9 on 2021-11-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rarerestapi', '0004_auto_20211117_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='category_id',
            new_name='category',
        ),
    ]
